### ISSUE TITLE
regression.aictest error

### ISSUE THREAD

**Issue by Slaapkamer** [christophsax/seasonal#249] opened 2020-09-08 13:26 UTC
Hi, 

When I use the option regression.aictest = NULL in the seas command, I get the following error:

**Error in file(con, "r") : cannot open the connection**

If I don't use this option, the seas command works fine. The option seems to try to use a temp folder under my C:\Users\%username\AppData\Local\Temp\, which is not my R working directory. Any way to get around this?

Thank you.

**Comment by christophsax** [comment] 2020-09-16 09:49
Thanks. Which version are you using:


```r
packageVersion("seasonal")
```

**Comment by Slaapkamer** [comment] 2020-09-16 15:33
1.7.1

**Comment by christophsax** [comment] 2021-02-28 10:42
Not sure it this is still needed? Don't think there is anything special with this option. There may be some problems with you local settings, which may be tackled by running:

```{r}
seasonal::checkX13()
```

I am closing it otherwise, since I cannot reproduce.

**Closed by christophsax** 2021-02-28 10:42 UTC
