### ISSUE TITLE
Duplicate `row.names` in call to `summary(seas(AirPassengers))`

### ISSUE THREAD

**Issue by fjuniorr** [christophsax/seasonal#88] opened 2015-05-03 21:22 UTC
I'm trying to run the `seasonal::demo()` but I'm having problems with the summary call. When I run

```r
>library("seasonal")
>checkX13()
>m <- seas(AirPassengers)
>summary(m)
```

I get the following error

```r
>summary(m)
Error in read.table(text = z0, colClasses = "numeric") : 
  duplicate 'row.names' are not allowed
```

The traceback returned

```r
> traceback()
5: stop("duplicate 'row.names' are not allowed")
4: read.table(text = z0, colClasses = "numeric")
3: qs(object)
2: summary.seas(m)
1: summary(m)
```

Apparently the problem is happening because the call to `x$udg[grepl("^qs", names(x$udg))]` in the function `qs` produces a character vector with duplicate entries and this behaviour of `read.table`kicks in

```
If there is a header and the first row contains one fewer field than the number of columns, 
the first column in the input is used for the row names. Otherwise if row.names is missing, 
the rows are numbered.
```

Please let me know if I'm doing something wrong.

**Comment by christophsax** [comment] 2015-05-03 21:36
thanks for the report. This has been caused by an additional output in the new X-13 build (19) and is fixed in the latest dev version. To install from Github:

```
install.packages("devtools")       
devtools::install_github('christophsax/seasonal')  
```
Release on CRAN in about a week.

**Closed by christophsax** 2015-05-03 21:36 UTC
